<?php

$options = [
    CURLOPT_URL => $url_,
    CURLOPT_USERAGENT => getenv('USER_AGENT'),
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_FOLLOWLOCATION => 1,
    CURLOPT_MAXREDIRS => 3,
    CURLOPT_PATH_AS_IS => true,
    CURLOPT_TCP_FASTOPEN => true,
    CURLOPT_SSL_VERIFYPEER => false,
];
