<?php

include(dirname(__FILE__) . '/../classes/MyUtils.php');

$pid = getmypid();
$time_start = microtime(true);
error_log("${pid} START scripts/get_twitter_jaxa.php " . date('Y/m/d H:i:s'));

$mu = new MyUtils();

$rc = get_twitter_jaxa($mu);

error_log("${pid} FINISH " . substr((microtime(true) - $time_start), 0, 6) . 's');
exit();

function get_twitter_jaxa($mu_)
{
    $log_prefix = getmypid() . ' [' . __METHOD__ . '] ';

    $url = 'http://twitrss.me/twitter_user_to_rss/?user=JAXA_JP';
    $res = $mu_->get_contents($url);
    $res = simplexml_load_string($res, 'SimpleXMLElement', LIBXML_NOCDATA);
    // error_log(print_r($res, true));

    $rss_item = <<< __HEREDOC__
<item>
<guid>__GUID__</guid>
<pubDate>__PUBDATE__</pubDate>
<title>__TITLE__</title>
<link>__LINK__</link>
<description><![CDATA[__DESCRIPTION__]]></description>
</item>
__HEREDOC__;

    $rss_items = [];
    foreach ($res->channel->item as $item) {
        error_log($log_prefix . print_r($item, true));
        $description = $item->description;
        $rc = preg_match('/<img src="(.+?)".*?>/', $item->description, $match);
        if ($rc == 1) {
            $url = $match[1];
            $extension = pathinfo(parse_url($url, PHP_URL_PATH), PATHINFO_EXTENSION);
            $res1 = $mu_->get_contents($url);
            $filename = tempnam('/tmp', 'image_' . md5(microtime(true)));
            file_put_contents($filename, $res1);
            $rc = getimagesize($filename);
            error_log($log_prefix . print_r($rc, true));
            if (array_key_exists('mime', $rc) && substr($rc['mime'], 0, 6) == 'image/') {
                $extension = explode('/', $rc['mime'])[1];
            }
            if ($rc[0] > 600 && ($extension === 'png' || $extension === 'jpg' || $extension === 'jpeg')) {
                if ($extension == 'png') {
                    $im_org = imagecreatefrompng($filename);
                } else {
                    $im_org = imagecreatefromjpeg($filename);
                }
                $w = imagesx($im_org);
                $h = imagesy($im_org);
                $im_new = imagecreatetruecolor(600, 600 * $h / $w);
                imagecopyresampled($im_new, $im_org, 0, 0, 0, 0, 600, 600 * $h / $w, $w, $h);
                imagedestroy($im_org);
                imagejpeg($im_new, $filename, 85);
                imagedestroy($im_new);
                error_log($log_prefix . 'new size : ' . filesize($filename));
                if (filesize($filename) < strlen($res1)) {
                    $res1 = file_get_contents($filename);
                    $extension = 'jpeg';
                }
            }
            unlink($filename);
            $description = str_replace($match[0], '<img src="data:image/' . "${extension};base64," . base64_encode($res1) . '" />', $description);
        }
        $tmp = str_replace('__GUID__', $item->guid, $rss_item);
        $tmp = str_replace('__PUBDATE__', $item->pubDate, $tmp);
        $tmp = str_replace('__LINK__', $item->link, $tmp);
        $tmp = str_replace('__TITLE__', $item->title, $tmp);
        $tmp = str_replace('__DESCRIPTION__', $description, $tmp);

        if ((strlen(implode('', $rss_items)) + strlen($tmp)) > 900000) {
            break;
        }
        $rss_items[] = $tmp;
    }

    $xml_text = <<< __HEREDOC__
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <atom:link href="http://twitrss.me/twitter_user_to_rss/?user=JAXA_jp" rel="self" type="application/rss+xml" />
    <title>Twitter Search / JAXA_jp </title>
    <link>https://twitter.com/JAXA_jp</link>
    <description>Twitter feed for: JAXA_jp. Generated by TwitRSS.me</description>
    <language>en-us</language>
    <ttl>40</ttl>
    <image>
        <url>https://pbs.twimg.com/profile_images/528003479420153857/4EtZezKl_400x400.png</url>
    </image>
    __ITEMS__
  </channel>
</rss>
__HEREDOC__;

    $file = '/tmp/' . getenv('FC2_RSS_04') . '.xml';
    file_put_contents($file, str_replace('__ITEMS__', implode('', $rss_items), $xml_text));
    $mu_->upload_fc2($file);
    unlink($file);
}

function func_20190611b($mu_)
{
    $log_prefix = getmypid() . ' [' . __METHOD__ . '] ';

    $url = 'https://twitter.com/JAXA_jp';
    $res = $mu_->get_contents($url);

    $tweets = explode('<div class="js-tweet-text-container">', $res);
    array_shift($tweets);

    $rss_item = <<< __HEREDOC__
<item>
<guid isPermaLink="false">__HASH__</guid>
<pubDate>__PUBDATE__</pubDate>
<title>__TITLE__</title>
<link>http://dummy.local/</link>
<description>__DESCRIPTION__</description>
</item>
__HEREDOC__;

    $rss_items = [];
    foreach ($tweets as $one_tweet) {
        $rc = preg_match('/<p .+?>(.+?)<.+?<img data-aria-label-part src="(.+?)".+?data-time="(.+?)"/s', $one_tweet, $match);
        array_shift($match);
        if (count($match) === 0) {
            continue;
        }
        error_log($log_prefix . print_r($match, true));
        $url = $match[1];

        $res = $mu_->get_contents($url);
        error_log($log_prefix . 'original size : ' . strlen($res));
        $extension = pathinfo(parse_url($url, PHP_URL_PATH), PATHINFO_EXTENSION);
        $filename = tempnam('/tmp', 'image_' . md5(microtime(true)));
        file_put_contents($filename, $res);
        $rc = getimagesize($filename);
        error_log($log_prefix . print_r($rc, true));
        if (array_key_exists('mime', $rc) && substr($rc['mime'], 0, 6) == 'image/') {
            $extension = explode('/', $rc['mime'])[1];
        }
        if ($rc[0] > 600) {
            if ($extension == 'png') {
                $im_org = imagecreatefrompng($filename);
            } else {
                $im_org = imagecreatefromjpeg($filename);
            }
            $w = imagesx($im_org);
            $h = imagesy($im_org);
            $im_new = imagecreatetruecolor(600, 600 * $h / $w);
            imagecopyresampled($im_new, $im_org, 0, 0, 0, 0, 600, 600 * $h / $w, $w, $h);
            imagejpeg($im_new, $filename, 85);
            error_log($log_prefix . 'new size : ' . filesize($filename));
            if (filesize($filename) < strlen($res)) {
                $res = file_get_contents($filename);
                $extension = 'jpeg';
            }
        }
        unlink($filename);
        $description = '<img src="data:image/' . $extension . ';base64,' . base64_encode($res) . '" />';

        $tmp = str_replace('__DESCRIPTION__', $description, $rss_item);
        $tmp = str_replace('__TITLE__', htmlspecialchars($match[0]), $tmp);
        $tmp = str_replace('__PUBDATE__', date('D, j M Y G:i:s +0900', $match[2]), $tmp);
        $tmp = str_replace('__HASH__', hash('sha256', $description), $tmp);

        if ((strlen(implode('', $rss_items)) + strlen($tmp)) > 900000) {
            break;
        }

        $rss_items[] = $tmp;
    }

    $xml_text = <<< __HEREDOC__
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title>jaxa</title>
<link>http://dummy.local/</link>
<description>jaxa</description>
__ITEMS__
</channel>
</rss>
__HEREDOC__;

    $file = '/tmp/' . 'test.xml';
    file_put_contents($file, str_replace('__ITEMS__', implode('', $rss_items), $xml_text));
    $mu_->upload_fc2($file);
    error_log('filesize : ' . filesize($file));
    unlink($file);
}
